/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ordemservico.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Edesio Goncalves
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        informacoes = new javax.swing.JPanel();
        lblBemVindo = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        lblDataAcesso = new javax.swing.JLabel();
        lblNomeUsuarioAcesso = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        clienteMenuCadastro = new javax.swing.JMenuItem();
        OSMenuCadastro = new javax.swing.JMenuItem();
        usuarioMenuCadastro = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        servicosMenuRelatorio = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        sobreMenuAjuda = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        sairMenuOpcoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordem de Serviço - Home");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(882, 695));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        informacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        informacoes.setPreferredSize(new java.awt.Dimension(300, 700));

        lblBemVindo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        lblBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBemVindo.setText("Seja bem-vindo,");
        lblBemVindo.setPreferredSize(new java.awt.Dimension(250, 30));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ordemservico/icones/logoservico.png"))); // NOI18N

        lblDataAcesso.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        lblDataAcesso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataAcesso.setText("Data");
        lblDataAcesso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDataAcesso.setPreferredSize(new java.awt.Dimension(250, 30));

        lblNomeUsuarioAcesso.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        lblNomeUsuarioAcesso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeUsuarioAcesso.setText("Usuário");
        lblNomeUsuarioAcesso.setEnabled(false);
        lblNomeUsuarioAcesso.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout informacoesLayout = new javax.swing.GroupLayout(informacoes);
        informacoes.setLayout(informacoesLayout);
        informacoesLayout.setHorizontalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo)
                    .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeUsuarioAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        informacoesLayout.setVerticalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeUsuarioAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuCadastro.setText("Cadastro");

        clienteMenuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        clienteMenuCadastro.setText("Cliente");
        menuCadastro.add(clienteMenuCadastro);

        OSMenuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        OSMenuCadastro.setText("OS");
        menuCadastro.add(OSMenuCadastro);

        usuarioMenuCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        usuarioMenuCadastro.setText("Usuário");
        usuarioMenuCadastro.setEnabled(false);
        usuarioMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioMenuCadastroActionPerformed(evt);
            }
        });
        menuCadastro.add(usuarioMenuCadastro);

        menu.add(menuCadastro);

        menuRelatorio.setText("Relatório");
        menuRelatorio.setEnabled(false);

        servicosMenuRelatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        servicosMenuRelatorio.setText("Serviços");
        menuRelatorio.add(servicosMenuRelatorio);

        menu.add(menuRelatorio);

        menuAjuda.setText("Ajuda");

        sobreMenuAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        sobreMenuAjuda.setText("Sobre");
        sobreMenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuAjudaActionPerformed(evt);
            }
        });
        menuAjuda.add(sobreMenuAjuda);

        menu.add(menuAjuda);

        menuOpcoes.setText("Opções");

        sairMenuOpcoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sairMenuOpcoes.setText("Sair");
        sairMenuOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuOpcoesActionPerformed(evt);
            }
        });
        menuOpcoes.add(sairMenuOpcoes);

        menu.add(menuOpcoes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        setSize(new java.awt.Dimension(1208, 782));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioMenuCadastroActionPerformed
        // TODO add your handling code here:
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_usuarioMenuCadastroActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblDataAcesso.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void sairMenuOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuOpcoesActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_sairMenuOpcoesActionPerformed

    private void sobreMenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuAjudaActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_sobreMenuAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OSMenuCadastro;
    private javax.swing.JMenuItem clienteMenuCadastro;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JPanel informacoes;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblDataAcesso;
    public static javax.swing.JLabel lblNomeUsuarioAcesso;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuOpcoes;
    public static javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem sairMenuOpcoes;
    private javax.swing.JMenuItem servicosMenuRelatorio;
    private javax.swing.JMenuItem sobreMenuAjuda;
    public static javax.swing.JMenuItem usuarioMenuCadastro;
    // End of variables declaration//GEN-END:variables
}
